// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var problem_notify, sendFile, setup, upload_file;
    problem_notify = function() {
      $('html').removeClass('uploading');
      $('html').removeClass('drag-hover');
      $('html').addClass('error');
      window.setTimeout(function() {
        $('html').removeClass('error');
        $('.uploader').show(100);
        return $('.upload_notify').hide(100);
      }, 2000);
      return $('.error_notify').show(100).delay(2000).hide(100);
    };
    upload_file = function(file, signed_request, url) {
      var xhr;
      xhr = new XMLHttpRequest;
      xhr.open('PUT', signed_request);
      xhr.onload = function() {
        if (xhr.status === 200) {
          $('.uploader').show(100);
          $('.upload_notify').hide(100);
          $('html').removeClass('drag-hover');
          $('html').removeClass('uploading');
          return window.location = "http://s.shapetape.xyz/" + url;
        }
      };
      xhr.onerror = function() {
        return problem_notify();
      };
      return xhr.send(file);
    };
    sendFile = function(file) {
      $('html').removeClass('drag-hover');
      $('html').addClass('uploading');
      $('.uploader').hide(100);
      $('.upload_notify').show(100);
      return $.get('/upload_request.php', {}, function(data) {
        if (data.request != null) {
          return upload_file(file, data.request, data.url);
        } else {
          return problem_notify();
        }
      });
    };
    setup = function() {
      var html;
      $('#file_upload_button').click(function() {
        return sendFile($('#file_input').files[0]);
      });
      html = $('html');
      html.addClass('ready');
      html.on("dragover", function() {
        return html.addClass('drag-hover');
      });
      html.on("dragleave", function() {
        return html.removeClass('drag-hover');
      });
      window.addEventListener('dragover', (function(e) {
        e = e || event;
        e.preventDefault();
      }), false);
      return window.addEventListener('drop', (function(e) {
        e = e || event;
        e.preventDefault();
        sendFile(e.dataTransfer.files[0]);
      }), false);
    };
    return $(function() {
      return setup();
    });
  })();

}).call(this);
