// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var curDown, curXPos, curYPos, img_container, placeholder, slideValue, toggleImg, toggleVec, vector, zooming;
    img_container = $('#img-container');
    vector = $('#vector');
    placeholder = $('#placeholder');
    $('#vector, #placeholder, .small-logo').on('dragstart', function(event) {
      return event.preventDefault();
    });
    toggleImg = function() {
      placeholder.show();
      return vector.hide();
    };
    toggleVec = function() {
      placeholder.hide();
      return vector.show();
    };
    toggleVec();
    slideValue = 90;
    zooming = false;
    $('.slider').on('input', function() {
      if (!zooming) {
        toggleImg();
        zooming = true;
      }
      slideValue = this.value;
      return img_container.css('width', slideValue + "%");
    });
    $('.slider').on('mouseup', function() {
      if (zooming) {
        toggleVec();
        zooming = false;
      }
      return true;
    });
    curYPos = 0;
    curXPos = 0;
    curDown = false;
    window.addEventListener('mousemove', function(e) {
      if (!zooming && curDown) {
        window.scrollTo(document.body.scrollLeft + curXPos - e.pageX, document.body.scrollTop + curYPos - e.pageY);
      }
      return true;
    });
    window.addEventListener('mousedown', function(e) {
      if (!zooming && e.clientY > 65) {
        curDown = true;
        curYPos = e.pageY;
        curXPos = e.pageX;
      }
      return true;
    });
    return window.addEventListener('mouseup', function(e) {
      curDown = false;
      return true;
    });
  });

}).call(this);
